config/routes.rb
Rails.application.routes.draw do
  resources :intentions, only: [:new, :create, :edit, :update, :destroy]
  resources :user_posts, only: [:create, :destroy]
  resources :post_categories, only: [:create]
  resources :posts
  # resources :categories
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  get '/signin', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#logout', as: 'logout'
  post '/signin', to: 'sessions#create_then_user'
  post '/signin_to_posts', to: 'sessions#create_then_posts'
  patch '/change_intention_status/:id', to: 'intentions#change_status', as: 'change_intention_status'
  post '/filter', to: 'posts#filter_to_index'
  get '/welcome', to: 'static_pages#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def welcome
    render 'welcome'
  end

end

app/views/static_pages/welcome.erb
<div class="main-wrapper">
<h1>Welcome to WellnessHub!</h1>

<div class="post">
  <p>
    With WellnessHub, you can...
    <ul>
      <li>Set Wellness Intentions For Yourself</li>
      <li>Post Links to Wellenss Resources</li>
      <li>Browse Other Peoples Shared Posts</li>
      <li>Save Posts to Your List and Organize Them by Intention</li>
      <li>BE WELL</li>
    </ul>
  </p>

<div>
<button><%= link_to 'Login', login_path %></button>
OR
<button><%= link_to 'Create an Account', new_user_path %></button>
<div>
</div>
</div>