config/routes.rb
Rails.application.routes.draw do
  resources :intentions, only: [:new, :create, :edit, :update, :destroy]
  resources :user_posts, only: [:create, :destroy]
  resources :post_categories, only: [:create]
  resources :posts
  # resources :categories
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  get '/signin', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#logout', as: 'logout'
  post '/signin', to: 'sessions#create_then_user'
  post '/signin_to_posts', to: 'sessions#create_then_posts'
  patch '/change_intention_status/:id', to: 'intentions#change_status', as: 'change_intention_status'
  post '/filter', to: 'posts#filter_to_index'
  get '/welcome', to: 'static_pages#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :owned_posts, foreign_key: "owner_id", class_name: "Post"
  has_many :intentions
  has_many :user_posts, through: :intentions
  has_many :posts, through: :user_posts

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:edit, :update, :destroy]
  before_action :require_login, only: [:show, :edit, :update, :destroy]

  def show

    if session[:user_id]!=params[:id]
      redirect_to user_path(session[:user_id])
      return
    end

    @user = current_user

    @complete_intentions = current_user.intentions.select {|intention| intention.complete == true}
    @incomplete_intentions = current_user.intentions.select {|intention| intention.complete == false}
    @all_intentions = [@incomplete_intentions, @complete_intentions]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to '/logout'
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user.destroy
    redirect_to new_user_path
    # THIS PATH SHOULD BE UPDATED ONCE WE HAVE A LOGIN PAGE OR SOMETHING
  end

  private

    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.erb
<h1> Edit User </h1>

<div class="main-wrapper">
<%= form_for @user, html: {class:'form'} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.submit %>
<% end %>

<p>
<%= form_for @user, method: 'DELETE', html: {class:'form delete'} do |f| %>
  <%= f.submit 'Delete User' %>
<% end %>
</p>
</div>

app/views/users/new.erb
<div class="main-wrapper">
<h1> Create New User </h1>

<%= form_for @user, html: {class: "form"} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.submit %>
<% end %>
</div>

app/views/users/show.erb
<div class="main-wrapper">
<h1> Welcome, <%= @user.name %>! </h1>

<br>
<div>
  <% if flash[:messages] %>
    <%= flash[:messages] %>
  <% end %>
</div>
<div class="user-top">
<h2>My Wellness Intentions:</h2>

<% if @user.intentions.empty? %>
  <%= "You haven't set any intentions yet!" %>
<div>
  <%= link_to 'Set an Intention', new_intention_path %>
</div>
<% else %>

    <% @user.intentions.each do |intention| %>
     <%= intention.name %>: <%= pluralize(intention.posts_count, 'Post') %><br>
      <% end %>
    <br>
  </div>


  <% @all_intentions.each do |intention_group| %>
    <% if intention_group == @incomplete_intentions %>
      <h2 class=header><%= 'Incomplete Intentions' %></h2>
    <% else %>
      <h2 class=header><%= 'Complete Intentions' %></h2>
    <% end %>

    <% intention_group.each do |intention| %>

     <div class="intention">
       <div class="header-intention">
      <h5> <%= intention.complete == true ? 'COMPLETE' : 'INCOMPLETE' %> </h5>

       <h3><%= intention.name %></h3>

     <%= form_for intention, method: 'patch', url: change_intention_status_path(intention) do |f| %>
       <% if intention.complete == false %>
        <%= f.submit 'Mark as Complete' %>
       <% else %>
        <%= f.submit 'Mark as Incomplete' %>
      <% end %>
     <% end %>
     </div>


      <%intention.posts.each do |post| %><br>
      <div class=post>
        <h3 class="post-title"><%= link_to post.title, post_path(post)%></h3>
        <div class="post-comment"><%= post.comment %><br></div>
        <%=link_to post.url, post.url %><br>

      <div class="post-button">
        <% @user_post = UserPost.find_by(user_id: session[:user_id], post_id: post.id, intention_id: intention.id) %>
        <%= form_for post, method: 'delete', url: user_post_path(@user_post) do |f| %>
          <%= f.submit 'Remove Post From Intention'%>
        <% end %>
      </div>

      </div>
      <% end %>


      <p><button><%= link_to 'Edit Intention', edit_intention_path(intention) %></button></p>
        </div>
    <% end %>

  <% end %>
<% end %>
  </div>