config/routes.rb
Rails.application.routes.draw do
  resources :intentions, only: [:new, :create, :edit, :update, :destroy]
  resources :user_posts, only: [:create, :destroy]
  resources :post_categories, only: [:create]
  resources :posts
  # resources :categories
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  get '/signin', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#logout', as: 'logout'
  post '/signin', to: 'sessions#create_then_user'
  post '/signin_to_posts', to: 'sessions#create_then_posts'
  patch '/change_intention_status/:id', to: 'intentions#change_status', as: 'change_intention_status'
  post '/filter', to: 'posts#filter_to_index'
  get '/welcome', to: 'static_pages#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WellnessHub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>


  <body>
<div class="nav-bar">
<ul>

    <% if session[:user_id]%>
    <li>
          <%= link_to "My Wellness Hub", user_path(session[:user_id]) %> </h3></li>

          <% end %>
    <li> <%= link_to "Browse Wellness Posts", posts_path %> </li>
    <% if session[:user_id]%>
      <li> <%= link_to "Set a New Intention", new_intention_path %> </li>
    <% end %>
    <% if session[:user_id] %>
    <li><%= link_to "Share a Resource", new_post_path %> </h3></li>
      <li> <%= link_to "Logout", logout_path %></li>
    <% end %>
  <% if @user && @user.id %>
  <li> Logged in as <%=@user.name%>
    <button> <%= link_to "Edit User", edit_user_path(@user) %> </button></li>
  <% end %>
</ul>
    </div>


    <%= yield %>

  </body>
</html>